/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.capgemini.proyecto.procesopedido.sb.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import es.capgemini.proyecto.procesopedido.sb.model.Pedidos;
import es.capgemini.proyecto.procesopedido.sb.model.PedidosModel;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Pedidos service. Represents a row in the &quot;PROYECTO_Pedidos&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PedidosModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PedidosImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PedidosImpl
 * @generated
 */
@JSON(strict = true)
public class PedidosModelImpl
	extends BaseModelImpl<Pedidos> implements PedidosModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a pedidos model instance should use the <code>Pedidos</code> interface instead.
	 */
	public static final String TABLE_NAME = "PROYECTO_Pedidos";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"id_", Types.BIGINT},
		{"idUsuario", Types.BIGINT}, {"email", Types.VARCHAR},
		{"nombre", Types.VARCHAR}, {"via", Types.VARCHAR},
		{"direccion", Types.VARCHAR}, {"pais", Types.VARCHAR},
		{"provincia", Types.VARCHAR}, {"ciudad", Types.VARCHAR},
		{"codipoPostal", Types.VARCHAR}, {"idProducto", Types.BIGINT},
		{"precio", Types.DOUBLE}, {"cantidad", Types.INTEGER}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("idUsuario", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("email", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nombre", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("via", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("direccion", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pais", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("provincia", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ciudad", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("codipoPostal", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idProducto", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("precio", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("cantidad", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE =
		"create table PROYECTO_Pedidos (uuid_ VARCHAR(75) null,id_ LONG not null primary key,idUsuario LONG,email VARCHAR(75) null,nombre VARCHAR(75) null,via VARCHAR(75) null,direccion VARCHAR(75) null,pais VARCHAR(75) null,provincia VARCHAR(75) null,ciudad VARCHAR(75) null,codipoPostal VARCHAR(75) null,idProducto LONG,precio DOUBLE,cantidad INTEGER)";

	public static final String TABLE_SQL_DROP = "drop table PROYECTO_Pedidos";

	public static final String ORDER_BY_JPQL = " ORDER BY pedidos.nombre ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY PROYECTO_Pedidos.nombre ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDPRODUCTO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long IDUSUARIO_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NOMBRE_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PedidosModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Pedidos.class;
	}

	@Override
	public String getModelClassName() {
		return Pedidos.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Pedidos, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Pedidos, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Pedidos, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Pedidos)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Pedidos, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Pedidos, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(Pedidos)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Pedidos, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Pedidos, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<Pedidos, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Pedidos, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Pedidos, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Pedidos, Object>>();
		Map<String, BiConsumer<Pedidos, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Pedidos, ?>>();

		attributeGetterFunctions.put("uuid", Pedidos::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Pedidos, String>)Pedidos::setUuid);
		attributeGetterFunctions.put("id", Pedidos::getId);
		attributeSetterBiConsumers.put(
			"id", (BiConsumer<Pedidos, Long>)Pedidos::setId);
		attributeGetterFunctions.put("idUsuario", Pedidos::getIdUsuario);
		attributeSetterBiConsumers.put(
			"idUsuario", (BiConsumer<Pedidos, Long>)Pedidos::setIdUsuario);
		attributeGetterFunctions.put("email", Pedidos::getEmail);
		attributeSetterBiConsumers.put(
			"email", (BiConsumer<Pedidos, String>)Pedidos::setEmail);
		attributeGetterFunctions.put("nombre", Pedidos::getNombre);
		attributeSetterBiConsumers.put(
			"nombre", (BiConsumer<Pedidos, String>)Pedidos::setNombre);
		attributeGetterFunctions.put("via", Pedidos::getVia);
		attributeSetterBiConsumers.put(
			"via", (BiConsumer<Pedidos, String>)Pedidos::setVia);
		attributeGetterFunctions.put("direccion", Pedidos::getDireccion);
		attributeSetterBiConsumers.put(
			"direccion", (BiConsumer<Pedidos, String>)Pedidos::setDireccion);
		attributeGetterFunctions.put("pais", Pedidos::getPais);
		attributeSetterBiConsumers.put(
			"pais", (BiConsumer<Pedidos, String>)Pedidos::setPais);
		attributeGetterFunctions.put("provincia", Pedidos::getProvincia);
		attributeSetterBiConsumers.put(
			"provincia", (BiConsumer<Pedidos, String>)Pedidos::setProvincia);
		attributeGetterFunctions.put("ciudad", Pedidos::getCiudad);
		attributeSetterBiConsumers.put(
			"ciudad", (BiConsumer<Pedidos, String>)Pedidos::setCiudad);
		attributeGetterFunctions.put("codipoPostal", Pedidos::getCodipoPostal);
		attributeSetterBiConsumers.put(
			"codipoPostal",
			(BiConsumer<Pedidos, String>)Pedidos::setCodipoPostal);
		attributeGetterFunctions.put("idProducto", Pedidos::getIdProducto);
		attributeSetterBiConsumers.put(
			"idProducto", (BiConsumer<Pedidos, Long>)Pedidos::setIdProducto);
		attributeGetterFunctions.put("precio", Pedidos::getPrecio);
		attributeSetterBiConsumers.put(
			"precio", (BiConsumer<Pedidos, Double>)Pedidos::setPrecio);
		attributeGetterFunctions.put("cantidad", Pedidos::getCantidad);
		attributeSetterBiConsumers.put(
			"cantidad", (BiConsumer<Pedidos, Integer>)Pedidos::setCantidad);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_id = id;
	}

	@JSON
	@Override
	public long getIdUsuario() {
		return _idUsuario;
	}

	@Override
	public void setIdUsuario(long idUsuario) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idUsuario = idUsuario;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdUsuario() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idUsuario"));
	}

	@JSON
	@Override
	public String getEmail() {
		if (_email == null) {
			return "";
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_email = email;
	}

	@JSON
	@Override
	public String getNombre() {
		if (_nombre == null) {
			return "";
		}
		else {
			return _nombre;
		}
	}

	@Override
	public void setNombre(String nombre) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_nombre = nombre;
	}

	@JSON
	@Override
	public String getVia() {
		if (_via == null) {
			return "";
		}
		else {
			return _via;
		}
	}

	@Override
	public void setVia(String via) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_via = via;
	}

	@JSON
	@Override
	public String getDireccion() {
		if (_direccion == null) {
			return "";
		}
		else {
			return _direccion;
		}
	}

	@Override
	public void setDireccion(String direccion) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_direccion = direccion;
	}

	@JSON
	@Override
	public String getPais() {
		if (_pais == null) {
			return "";
		}
		else {
			return _pais;
		}
	}

	@Override
	public void setPais(String pais) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_pais = pais;
	}

	@JSON
	@Override
	public String getProvincia() {
		if (_provincia == null) {
			return "";
		}
		else {
			return _provincia;
		}
	}

	@Override
	public void setProvincia(String provincia) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_provincia = provincia;
	}

	@JSON
	@Override
	public String getCiudad() {
		if (_ciudad == null) {
			return "";
		}
		else {
			return _ciudad;
		}
	}

	@Override
	public void setCiudad(String ciudad) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ciudad = ciudad;
	}

	@JSON
	@Override
	public String getCodipoPostal() {
		if (_codipoPostal == null) {
			return "";
		}
		else {
			return _codipoPostal;
		}
	}

	@Override
	public void setCodipoPostal(String codipoPostal) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_codipoPostal = codipoPostal;
	}

	@JSON
	@Override
	public long getIdProducto() {
		return _idProducto;
	}

	@Override
	public void setIdProducto(long idProducto) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_idProducto = idProducto;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalIdProducto() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("idProducto"));
	}

	@JSON
	@Override
	public double getPrecio() {
		return _precio;
	}

	@Override
	public void setPrecio(double precio) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_precio = precio;
	}

	@JSON
	@Override
	public int getCantidad() {
		return _cantidad;
	}

	@Override
	public void setCantidad(int cantidad) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_cantidad = cantidad;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Pedidos.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Pedidos toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Pedidos>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PedidosImpl pedidosImpl = new PedidosImpl();

		pedidosImpl.setUuid(getUuid());
		pedidosImpl.setId(getId());
		pedidosImpl.setIdUsuario(getIdUsuario());
		pedidosImpl.setEmail(getEmail());
		pedidosImpl.setNombre(getNombre());
		pedidosImpl.setVia(getVia());
		pedidosImpl.setDireccion(getDireccion());
		pedidosImpl.setPais(getPais());
		pedidosImpl.setProvincia(getProvincia());
		pedidosImpl.setCiudad(getCiudad());
		pedidosImpl.setCodipoPostal(getCodipoPostal());
		pedidosImpl.setIdProducto(getIdProducto());
		pedidosImpl.setPrecio(getPrecio());
		pedidosImpl.setCantidad(getCantidad());

		pedidosImpl.resetOriginalValues();

		return pedidosImpl;
	}

	@Override
	public Pedidos cloneWithOriginalValues() {
		PedidosImpl pedidosImpl = new PedidosImpl();

		pedidosImpl.setUuid(this.<String>getColumnOriginalValue("uuid_"));
		pedidosImpl.setId(this.<Long>getColumnOriginalValue("id_"));
		pedidosImpl.setIdUsuario(
			this.<Long>getColumnOriginalValue("idUsuario"));
		pedidosImpl.setEmail(this.<String>getColumnOriginalValue("email"));
		pedidosImpl.setNombre(this.<String>getColumnOriginalValue("nombre"));
		pedidosImpl.setVia(this.<String>getColumnOriginalValue("via"));
		pedidosImpl.setDireccion(
			this.<String>getColumnOriginalValue("direccion"));
		pedidosImpl.setPais(this.<String>getColumnOriginalValue("pais"));
		pedidosImpl.setProvincia(
			this.<String>getColumnOriginalValue("provincia"));
		pedidosImpl.setCiudad(this.<String>getColumnOriginalValue("ciudad"));
		pedidosImpl.setCodipoPostal(
			this.<String>getColumnOriginalValue("codipoPostal"));
		pedidosImpl.setIdProducto(
			this.<Long>getColumnOriginalValue("idProducto"));
		pedidosImpl.setPrecio(this.<Double>getColumnOriginalValue("precio"));
		pedidosImpl.setCantidad(
			this.<Integer>getColumnOriginalValue("cantidad"));

		return pedidosImpl;
	}

	@Override
	public int compareTo(Pedidos pedidos) {
		int value = 0;

		value = getNombre().compareTo(pedidos.getNombre());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Pedidos)) {
			return false;
		}

		Pedidos pedidos = (Pedidos)object;

		long primaryKey = pedidos.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Pedidos> toCacheModel() {
		PedidosCacheModel pedidosCacheModel = new PedidosCacheModel();

		pedidosCacheModel.uuid = getUuid();

		String uuid = pedidosCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			pedidosCacheModel.uuid = null;
		}

		pedidosCacheModel.id = getId();

		pedidosCacheModel.idUsuario = getIdUsuario();

		pedidosCacheModel.email = getEmail();

		String email = pedidosCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			pedidosCacheModel.email = null;
		}

		pedidosCacheModel.nombre = getNombre();

		String nombre = pedidosCacheModel.nombre;

		if ((nombre != null) && (nombre.length() == 0)) {
			pedidosCacheModel.nombre = null;
		}

		pedidosCacheModel.via = getVia();

		String via = pedidosCacheModel.via;

		if ((via != null) && (via.length() == 0)) {
			pedidosCacheModel.via = null;
		}

		pedidosCacheModel.direccion = getDireccion();

		String direccion = pedidosCacheModel.direccion;

		if ((direccion != null) && (direccion.length() == 0)) {
			pedidosCacheModel.direccion = null;
		}

		pedidosCacheModel.pais = getPais();

		String pais = pedidosCacheModel.pais;

		if ((pais != null) && (pais.length() == 0)) {
			pedidosCacheModel.pais = null;
		}

		pedidosCacheModel.provincia = getProvincia();

		String provincia = pedidosCacheModel.provincia;

		if ((provincia != null) && (provincia.length() == 0)) {
			pedidosCacheModel.provincia = null;
		}

		pedidosCacheModel.ciudad = getCiudad();

		String ciudad = pedidosCacheModel.ciudad;

		if ((ciudad != null) && (ciudad.length() == 0)) {
			pedidosCacheModel.ciudad = null;
		}

		pedidosCacheModel.codipoPostal = getCodipoPostal();

		String codipoPostal = pedidosCacheModel.codipoPostal;

		if ((codipoPostal != null) && (codipoPostal.length() == 0)) {
			pedidosCacheModel.codipoPostal = null;
		}

		pedidosCacheModel.idProducto = getIdProducto();

		pedidosCacheModel.precio = getPrecio();

		pedidosCacheModel.cantidad = getCantidad();

		return pedidosCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Pedidos, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Pedidos, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Pedidos, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((Pedidos)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Pedidos, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Pedidos, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Pedidos, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Pedidos)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Pedidos>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					Pedidos.class, ModelWrapper.class);

	}

	private String _uuid;
	private long _id;
	private long _idUsuario;
	private String _email;
	private String _nombre;
	private String _via;
	private String _direccion;
	private String _pais;
	private String _provincia;
	private String _ciudad;
	private String _codipoPostal;
	private long _idProducto;
	private double _precio;
	private int _cantidad;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Pedidos, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Pedidos)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("id_", _id);
		_columnOriginalValues.put("idUsuario", _idUsuario);
		_columnOriginalValues.put("email", _email);
		_columnOriginalValues.put("nombre", _nombre);
		_columnOriginalValues.put("via", _via);
		_columnOriginalValues.put("direccion", _direccion);
		_columnOriginalValues.put("pais", _pais);
		_columnOriginalValues.put("provincia", _provincia);
		_columnOriginalValues.put("ciudad", _ciudad);
		_columnOriginalValues.put("codipoPostal", _codipoPostal);
		_columnOriginalValues.put("idProducto", _idProducto);
		_columnOriginalValues.put("precio", _precio);
		_columnOriginalValues.put("cantidad", _cantidad);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");
		attributeNames.put("id_", "id");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("id_", 2L);

		columnBitmasks.put("idUsuario", 4L);

		columnBitmasks.put("email", 8L);

		columnBitmasks.put("nombre", 16L);

		columnBitmasks.put("via", 32L);

		columnBitmasks.put("direccion", 64L);

		columnBitmasks.put("pais", 128L);

		columnBitmasks.put("provincia", 256L);

		columnBitmasks.put("ciudad", 512L);

		columnBitmasks.put("codipoPostal", 1024L);

		columnBitmasks.put("idProducto", 2048L);

		columnBitmasks.put("precio", 4096L);

		columnBitmasks.put("cantidad", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Pedidos _escapedModel;

}