/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.capgemini.proyecto.procesopedido.sb.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Pedidos service. Represents a row in the &quot;PROYECTO_Pedidos&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>es.capgemini.proyecto.procesopedido.sb.model.impl.PedidosModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>es.capgemini.proyecto.procesopedido.sb.model.impl.PedidosImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Pedidos
 * @generated
 */
@ProviderType
public interface PedidosModel extends BaseModel<Pedidos> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a pedidos model instance should use the {@link Pedidos} interface instead.
	 */

	/**
	 * Returns the primary key of this pedidos.
	 *
	 * @return the primary key of this pedidos
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this pedidos.
	 *
	 * @param primaryKey the primary key of this pedidos
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this pedidos.
	 *
	 * @return the uuid of this pedidos
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this pedidos.
	 *
	 * @param uuid the uuid of this pedidos
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this pedidos.
	 *
	 * @return the ID of this pedidos
	 */
	public long getId();

	/**
	 * Sets the ID of this pedidos.
	 *
	 * @param id the ID of this pedidos
	 */
	public void setId(long id);

	/**
	 * Returns the id usuario of this pedidos.
	 *
	 * @return the id usuario of this pedidos
	 */
	public long getIdUsuario();

	/**
	 * Sets the id usuario of this pedidos.
	 *
	 * @param idUsuario the id usuario of this pedidos
	 */
	public void setIdUsuario(long idUsuario);

	/**
	 * Returns the email of this pedidos.
	 *
	 * @return the email of this pedidos
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this pedidos.
	 *
	 * @param email the email of this pedidos
	 */
	public void setEmail(String email);

	/**
	 * Returns the nombre of this pedidos.
	 *
	 * @return the nombre of this pedidos
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this pedidos.
	 *
	 * @param nombre the nombre of this pedidos
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the via of this pedidos.
	 *
	 * @return the via of this pedidos
	 */
	@AutoEscape
	public String getVia();

	/**
	 * Sets the via of this pedidos.
	 *
	 * @param via the via of this pedidos
	 */
	public void setVia(String via);

	/**
	 * Returns the direccion of this pedidos.
	 *
	 * @return the direccion of this pedidos
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this pedidos.
	 *
	 * @param direccion the direccion of this pedidos
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the pais of this pedidos.
	 *
	 * @return the pais of this pedidos
	 */
	@AutoEscape
	public String getPais();

	/**
	 * Sets the pais of this pedidos.
	 *
	 * @param pais the pais of this pedidos
	 */
	public void setPais(String pais);

	/**
	 * Returns the provincia of this pedidos.
	 *
	 * @return the provincia of this pedidos
	 */
	@AutoEscape
	public String getProvincia();

	/**
	 * Sets the provincia of this pedidos.
	 *
	 * @param provincia the provincia of this pedidos
	 */
	public void setProvincia(String provincia);

	/**
	 * Returns the ciudad of this pedidos.
	 *
	 * @return the ciudad of this pedidos
	 */
	@AutoEscape
	public String getCiudad();

	/**
	 * Sets the ciudad of this pedidos.
	 *
	 * @param ciudad the ciudad of this pedidos
	 */
	public void setCiudad(String ciudad);

	/**
	 * Returns the codipo postal of this pedidos.
	 *
	 * @return the codipo postal of this pedidos
	 */
	@AutoEscape
	public String getCodipoPostal();

	/**
	 * Sets the codipo postal of this pedidos.
	 *
	 * @param codipoPostal the codipo postal of this pedidos
	 */
	public void setCodipoPostal(String codipoPostal);

	/**
	 * Returns the id producto of this pedidos.
	 *
	 * @return the id producto of this pedidos
	 */
	public long getIdProducto();

	/**
	 * Sets the id producto of this pedidos.
	 *
	 * @param idProducto the id producto of this pedidos
	 */
	public void setIdProducto(long idProducto);

	/**
	 * Returns the precio of this pedidos.
	 *
	 * @return the precio of this pedidos
	 */
	public double getPrecio();

	/**
	 * Sets the precio of this pedidos.
	 *
	 * @param precio the precio of this pedidos
	 */
	public void setPrecio(double precio);

	/**
	 * Returns the cantidad of this pedidos.
	 *
	 * @return the cantidad of this pedidos
	 */
	public int getCantidad();

	/**
	 * Sets the cantidad of this pedidos.
	 *
	 * @param cantidad the cantidad of this pedidos
	 */
	public void setCantidad(int cantidad);

	@Override
	public Pedidos cloneWithOriginalValues();

}