/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.capgemini.practicas.sb.tienda.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Tienda service. Represents a row in the &quot;PRACTICA_Tienda&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>es.capgemini.practicas.sb.tienda.model.impl.TiendaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>es.capgemini.practicas.sb.tienda.model.impl.TiendaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Tienda
 * @generated
 */
@ProviderType
public interface TiendaModel extends BaseModel<Tienda> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tienda model instance should use the {@link Tienda} interface instead.
	 */

	/**
	 * Returns the primary key of this tienda.
	 *
	 * @return the primary key of this tienda
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tienda.
	 *
	 * @param primaryKey the primary key of this tienda
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this tienda.
	 *
	 * @return the uuid of this tienda
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this tienda.
	 *
	 * @param uuid the uuid of this tienda
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this tienda.
	 *
	 * @return the ID of this tienda
	 */
	public long getId();

	/**
	 * Sets the ID of this tienda.
	 *
	 * @param id the ID of this tienda
	 */
	public void setId(long id);

	/**
	 * Returns the nombre of this tienda.
	 *
	 * @return the nombre of this tienda
	 */
	@AutoEscape
	public String getNombre();

	/**
	 * Sets the nombre of this tienda.
	 *
	 * @param nombre the nombre of this tienda
	 */
	public void setNombre(String nombre);

	/**
	 * Returns the direccion of this tienda.
	 *
	 * @return the direccion of this tienda
	 */
	@AutoEscape
	public String getDireccion();

	/**
	 * Sets the direccion of this tienda.
	 *
	 * @param direccion the direccion of this tienda
	 */
	public void setDireccion(String direccion);

	/**
	 * Returns the pais of this tienda.
	 *
	 * @return the pais of this tienda
	 */
	@AutoEscape
	public String getPais();

	/**
	 * Sets the pais of this tienda.
	 *
	 * @param pais the pais of this tienda
	 */
	public void setPais(String pais);

	/**
	 * Returns the provincia of this tienda.
	 *
	 * @return the provincia of this tienda
	 */
	@AutoEscape
	public String getProvincia();

	/**
	 * Sets the provincia of this tienda.
	 *
	 * @param provincia the provincia of this tienda
	 */
	public void setProvincia(String provincia);

	/**
	 * Returns the ciudad of this tienda.
	 *
	 * @return the ciudad of this tienda
	 */
	@AutoEscape
	public String getCiudad();

	/**
	 * Sets the ciudad of this tienda.
	 *
	 * @param ciudad the ciudad of this tienda
	 */
	public void setCiudad(String ciudad);

	/**
	 * Returns the codipo postal of this tienda.
	 *
	 * @return the codipo postal of this tienda
	 */
	@AutoEscape
	public String getCodipoPostal();

	/**
	 * Sets the codipo postal of this tienda.
	 *
	 * @param codipoPostal the codipo postal of this tienda
	 */
	public void setCodipoPostal(String codipoPostal);

	/**
	 * Returns the gerente of this tienda.
	 *
	 * @return the gerente of this tienda
	 */
	@AutoEscape
	public String getGerente();

	/**
	 * Sets the gerente of this tienda.
	 *
	 * @param gerente the gerente of this tienda
	 */
	public void setGerente(String gerente);

	@Override
	public Tienda cloneWithOriginalValues();

}